# Generated by Django 3.2.13 on 2022-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.CharField(max_length=500)),
            ],
        ),
    ]
