# Generated by Django 3.2.13 on 2022-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='no_of_books_issued',
            field=models.IntegerField(default=0),
        ),
    ]
