# Generated by Django 3.2.13 on 2022-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_desc', models.TextField()),
                ('book_author', models.CharField(max_length=200)),
                ('book_rental', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
