# Generated by Django 3.2.13 on 2022-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_quantity',
        ),
        migrations.AddField(
            model_name='books',
            name='no_of_time_issued',
            field=models.IntegerField(default=0),
        ),
    ]
