# Generated by Django 3.2.13 on 2022-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20220426_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_available',
            field=models.IntegerField(default=1),
        ),
    ]
