# Generated by Django 3.2.13 on 2022-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='no_of_books_issued',
        ),
        migrations.AddField(
            model_name='inventory',
            name='no_of_times_issued',
            field=models.IntegerField(default=0),
        ),
    ]
