# Generated by Django 3.2.13 on 2022-04-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20220426_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='no_of_times_issued',
        ),
    ]
